var Constants = {
    EMPLOYEES_LOAD_STARTED: "EMPLOYEES_LOAD_STARTED",
    EMPLOYEES_LOAD_SUCCEEDED: "EMPLOYEES_LOAD_SUCCEEDED",
    EMPLOYEES_LOAD_FAILED: "EMPLOYEES_LOAD_FAILED",

    EMPLOYEES_CREATE_STARTED: "EMPLOYEES_CREATE_STARTED",
    EMPLOYEES_CREATE_SUCCEEDED: "EMPLOYEES_CREATE_SUCCEEDED",
    EMPLOYEES_CREATE_FAILED: "EMPLOYEES_CREATE_FAILED",
};

module.exports = Constants;
